[package]
name = "ridl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
clap = "3.2.8"
strum = { version = "0.24.1", features = ["derive"] }
